package Interfaces;

import Database.Db_Cliente;
import Database.Db_ColaDoctor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seven
 */
public class ColaDoctor extends javax.swing.JFrame {
    
    Db_ColaDoctor cola = new Db_ColaDoctor();
    
    public ColaDoctor(){
            initComponents();
            Toolkit mipantalla = Toolkit.getDefaultToolkit(); // nos dice el medio donde esta compilando el programa
            Dimension tampantalla = mipantalla.getScreenSize(); // devuelve la dimension de la pantalla
            int altura = tampantalla.height, ancho = tampantalla.width;
            setLocation(ancho/4, altura/8);
        try {
            cola.llenarTabla(tablaPacientes);
        } catch (Exception ex) {
            Logger.getLogger(ColaDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ClienteTxt = new javax.swing.JTextField();
        PacienteTxt = new javax.swing.JTextField();
        btnTerminar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Titulo.setText("SISTEMA DE ATENCION");
        getContentPane().add(Titulo);
        Titulo.setBounds(170, 10, 150, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("LISTA DE ESPERA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 130, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("PACIENTE EN ATENCION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 200, 150, 14);

        jLabel3.setText("CLIENTE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 230, 70, 14);

        jLabel4.setText("PACIENTE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 260, 60, 14);

        ClienteTxt.setEditable(false);
        getContentPane().add(ClienteTxt);
        ClienteTxt.setBounds(140, 220, 270, 30);

        PacienteTxt.setEditable(false);
        getContentPane().add(PacienteTxt);
        PacienteTxt.setBounds(140, 250, 270, 30);

        btnTerminar.setText("TERMINAR ATENCION");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerminar);
        btnTerminar.setBounds(150, 330, 180, 40);

        btnAbrir.setText("ABRIR HISTORIAL MEDICO");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir);
        btnAbrir.setBounds(150, 290, 180, 30);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(410, 350, 100, 40);

        btnAtender.setText("ATENDER");
        btnAtender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtenderMouseClicked(evt);
            }
        });
        getContentPane().add(btnAtender);
        btnAtender.setBounds(360, 80, 120, 23);

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaPacientes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 60, 330, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        ClienteTxt.setText(null);
        PacienteTxt.setText(null);
        //Eliminar de la base de datos
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        inicio_Doctor doctor = new inicio_Doctor();
        doctor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        Db_Cliente db_cliente=new Db_Cliente();
        HistorialMedico historial_medico_ventana= new HistorialMedico();
        historial_medico_ventana.setVisible(true);
        String cliente=ClienteTxt.getText();
        String delimitadores= "[ .,;?!¡¿\'\"\\[\\]]+";
        String[] palabrasSeparadas = cliente.split(delimitadores);
        String nombre=palabrasSeparadas[0];
        String ApPaterno=palabrasSeparadas[1];
        String ApMaterno=palabrasSeparadas[2];
        
        try {
<<<<<<< HEAD:ProyectoVeterinaria/src/Interfaces/ColaDoctor.java
            File ruta = new File(HistorialTxt.getText());
            Desktop.getDesktop().open(ruta);
        } catch (IOException ex) {
            Logger.getLogger(ColaDoctor.class.getName()).log(Level.SEVERE, null, ex);
=======
            int id=db_cliente.buscar_idCliente(nombre, ApPaterno, ApMaterno);
            String ruta="D:/Historiales/DOC"+id+".txt";
            String texto;
      
            FileReader fr=new FileReader(ruta);
            BufferedReader br = new BufferedReader(fr);
            while((texto=br.readLine())!=null){
                    historial_medico_ventana.Historial_Area.setText(texto);
            }
            br.close();
            fr.close();
        } catch (Exception ex) {
            Logger.getLogger(SistemaAtencion.class.getName()).log(Level.SEVERE, null, ex);
>>>>>>> gerson:ProyectoVeterinaria/src/Interfaces/SistemaAtencion.java
        }
       
        historial_medico_ventana.setNombre(nombre);
        historial_medico_ventana.setApPaterno(ApPaterno);
        historial_medico_ventana.setApMaterno(ApMaterno);
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnAtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderMouseClicked
        ClienteTxt.setText((String) tablaPacientes.getValueAt(0, 0));
        PacienteTxt.setText((String) tablaPacientes.getValueAt(0, 1));
        DefaultTableModel modelo = (DefaultTableModel)tablaPacientes.getModel(); 
        modelo.removeRow(0);
    }//GEN-LAST:event_btnAtenderMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ClienteTxt;
    private javax.swing.JTextField PacienteTxt;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
