/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author User
 */
public class Factura extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cliente_Lbl = new javax.swing.JLabel();
        NombreCliente_Lbl = new javax.swing.JLabel();
        Nombre_Txt = new javax.swing.JTextField();
        ApPaterno_Lbl = new javax.swing.JLabel();
        ApPaterno_Txt = new javax.swing.JTextField();
        ApMaterno_Lbl = new javax.swing.JLabel();
        ApMaterno_Txt = new javax.swing.JTextField();
        Dni_Lbl = new javax.swing.JLabel();
        Dni_Txt = new javax.swing.JTextField();
        Direccion_Lbl = new javax.swing.JLabel();
        Direccion_Txt = new javax.swing.JTextField();
        TelCel_Lbl = new javax.swing.JLabel();
        TelCel_Txt = new javax.swing.JTextField();
        Mascota_Lbl = new javax.swing.JLabel();
        NombreMascota_Lbl = new javax.swing.JLabel();
        NombreMascota_Txt = new javax.swing.JTextField();
        Especie_Lbl = new javax.swing.JLabel();
        Especie_Txt = new javax.swing.JTextField();
        Raza_Lbl = new javax.swing.JLabel();
        Raza_Txt = new javax.swing.JTextField();
        Sexo_Lbl = new javax.swing.JLabel();
        Sexo_Txt = new javax.swing.JTextField();
        Id_Lbl = new javax.swing.JLabel();
        Id_Txt = new javax.swing.JTextField();
        FechaNac_Lbl = new javax.swing.JLabel();
        FechNacimiento_Txt = new javax.swing.JTextField();
        DesAtencion_Lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DesAtencion_TxtArea = new javax.swing.JTextArea();
        Precio_Lbl = new javax.swing.JLabel();
        Precio_Txt = new javax.swing.JTextField();
        Total_Lbl = new javax.swing.JLabel();
        Total_Txt = new javax.swing.JTextField();
        Salir_Btn = new javax.swing.JButton();
        Imprimir_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cliente_Lbl.setText("CLIENTE:");

        NombreCliente_Lbl.setText("NOMBRE:");

        Nombre_Txt.setEditable(false);

        ApPaterno_Lbl.setText("APELLIDO PATERNO:");

        ApPaterno_Txt.setEditable(false);

        ApMaterno_Lbl.setText("APELLIDO MATERNO:");

        ApMaterno_Txt.setEditable(false);

        Dni_Lbl.setText("DNI:");

        Dni_Txt.setEditable(false);

        Direccion_Lbl.setText("DIRECCION:");

        Direccion_Txt.setEditable(false);

        TelCel_Lbl.setText("TELEFONO/CELULAR:");

        TelCel_Txt.setEditable(false);

        Mascota_Lbl.setText("MASCOTA:");

        NombreMascota_Lbl.setText("NOMBRE:");

        NombreMascota_Txt.setEditable(false);

        Especie_Lbl.setText("ESPECIE:");

        Especie_Txt.setEditable(false);

        Raza_Lbl.setText("RAZA:");

        Raza_Txt.setEditable(false);

        Sexo_Lbl.setText("SEXO:");

        Sexo_Txt.setEditable(false);

        Id_Lbl.setText("ID:");

        Id_Txt.setEditable(false);

        FechaNac_Lbl.setText("FECHA DE NACIMIENTO:");

        FechNacimiento_Txt.setEditable(false);

        DesAtencion_Lbl.setText("DESCRIPCION DE ATENCION:");

        DesAtencion_TxtArea.setColumns(20);
        DesAtencion_TxtArea.setRows(5);
        jScrollPane1.setViewportView(DesAtencion_TxtArea);

        Precio_Lbl.setText("PRECIO");

        Total_Lbl.setText("TOTAL:");

        Salir_Btn.setText("SALIR");
        Salir_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_BtnActionPerformed(evt);
            }
        });

        Imprimir_Btn.setText("IMPRIMIR");
        Imprimir_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imprimir_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NombreCliente_Lbl)
                                            .addComponent(Dni_Lbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Nombre_Txt)
                                            .addComponent(Dni_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NombreMascota_Lbl)
                                            .addComponent(Cliente_Lbl)
                                            .addComponent(Mascota_Lbl)
                                            .addComponent(Id_Lbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NombreMascota_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                            .addComponent(Id_Txt))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ApPaterno_Lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ApPaterno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Direccion_Lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Direccion_Txt)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ApMaterno_Lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ApMaterno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TelCel_Lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TelCel_Txt))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FechaNac_Lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FechNacimiento_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(Especie_Lbl)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(Especie_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(Raza_Lbl)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(Raza_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(Total_Lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(8, 8, 8))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Salir_Btn)
                                                .addGap(19, 19, 19)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Sexo_Lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Sexo_Txt))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Precio_Lbl)
                                                    .addComponent(Total_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Imprimir_Btn)
                                                .addGap(21, 21, 21))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DesAtencion_Lbl)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(Precio_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cliente_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCliente_Lbl)
                    .addComponent(Nombre_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApPaterno_Lbl)
                    .addComponent(ApPaterno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApMaterno_Lbl)
                    .addComponent(ApMaterno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dni_Lbl)
                    .addComponent(Dni_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion_Lbl)
                    .addComponent(Direccion_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelCel_Lbl)
                    .addComponent(TelCel_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mascota_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreMascota_Lbl)
                    .addComponent(NombreMascota_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Especie_Lbl)
                    .addComponent(Especie_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Raza_Lbl)
                    .addComponent(Raza_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sexo_Lbl)
                    .addComponent(Sexo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_Lbl)
                    .addComponent(Id_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaNac_Lbl)
                    .addComponent(FechNacimiento_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DesAtencion_Lbl)
                            .addComponent(Precio_Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Precio_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total_Lbl)
                    .addComponent(Total_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir_Btn)
                    .addComponent(Imprimir_Btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Salir_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_BtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Salir_BtnActionPerformed

    private void Imprimir_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imprimir_BtnActionPerformed
        // TODO add your handling code here:
        PrinterJob imprimir = PrinterJob.getPrinterJob();
        imprimir.setPrintable(this);
        if(imprimir.printDialog()){
            try{
                imprimir.print();
            }catch(PrinterException ex){
                System.out.println("ERROR" + ex);
            }
        }
    }//GEN-LAST:event_Imprimir_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }
     public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException{
        if(pageIndex == 0){
            Graphics2D g2D = (Graphics2D) graphics;
            g2D.translate(pageFormat.getImageableX()+30, pageFormat.getImageableY()+30);
            g2D.scale(0.5, 0.5);
            this.printAll(graphics);
            return PAGE_EXISTS;
        }else return NO_SUCH_PAGE;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApMaterno_Lbl;
    private javax.swing.JTextField ApMaterno_Txt;
    private javax.swing.JLabel ApPaterno_Lbl;
    private javax.swing.JTextField ApPaterno_Txt;
    private javax.swing.JLabel Cliente_Lbl;
    private javax.swing.JLabel DesAtencion_Lbl;
    private javax.swing.JTextArea DesAtencion_TxtArea;
    private javax.swing.JLabel Direccion_Lbl;
    private javax.swing.JTextField Direccion_Txt;
    private javax.swing.JLabel Dni_Lbl;
    private javax.swing.JTextField Dni_Txt;
    private javax.swing.JLabel Especie_Lbl;
    private javax.swing.JTextField Especie_Txt;
    private javax.swing.JTextField FechNacimiento_Txt;
    private javax.swing.JLabel FechaNac_Lbl;
    private javax.swing.JLabel Id_Lbl;
    private javax.swing.JTextField Id_Txt;
    private javax.swing.JButton Imprimir_Btn;
    private javax.swing.JLabel Mascota_Lbl;
    private javax.swing.JLabel NombreCliente_Lbl;
    private javax.swing.JLabel NombreMascota_Lbl;
    private javax.swing.JTextField NombreMascota_Txt;
    private javax.swing.JTextField Nombre_Txt;
    private javax.swing.JLabel Precio_Lbl;
    private javax.swing.JTextField Precio_Txt;
    private javax.swing.JLabel Raza_Lbl;
    private javax.swing.JTextField Raza_Txt;
    private javax.swing.JButton Salir_Btn;
    private javax.swing.JLabel Sexo_Lbl;
    private javax.swing.JTextField Sexo_Txt;
    private javax.swing.JLabel TelCel_Lbl;
    private javax.swing.JTextField TelCel_Txt;
    private javax.swing.JLabel Total_Lbl;
    private javax.swing.JTextField Total_Txt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
