package Interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author usuario
 */
public class inicio_Doctor extends javax.swing.JFrame {

    /**
     * Creates new form inicio_Doctor
     */
    public inicio_Doctor() {
        initComponents();
        Toolkit mipantalla = Toolkit.getDefaultToolkit(); // nos dice el medio donde esta compilando el programa
        Dimension tampantalla = mipantalla.getScreenSize(); // devuelve la dimension de la pantalla
        int altura = tampantalla.height, ancho = tampantalla.width;
        setLocation(ancho/4, altura/8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Registrar_Usuario = new javax.swing.JButton();
        Btn_Mostrar_Cola = new javax.swing.JButton();
        Btn_Salir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Registrar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_Registrar_usuario.png"))); // NOI18N
        Btn_Registrar_Usuario.setMaximumSize(new java.awt.Dimension(115, 200));
        Btn_Registrar_Usuario.setMinimumSize(new java.awt.Dimension(115, 200));
        Btn_Registrar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Registrar_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, 190));

        Btn_Mostrar_Cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Bt_dog.png"))); // NOI18N
        Btn_Mostrar_Cola.setMaximumSize(new java.awt.Dimension(115, 200));
        Btn_Mostrar_Cola.setMinimumSize(new java.awt.Dimension(115, 200));
        Btn_Mostrar_Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Mostrar_ColaActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Mostrar_Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, 190));

        Btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_Salir.png"))); // NOI18N
        Btn_Salir.setMaximumSize(new java.awt.Dimension(115, 200));
        Btn_Salir.setMinimumSize(new java.awt.Dimension(115, 200));
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 90, 90));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo-Veterinario1.png"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(780, 580));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Registrar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_UsuarioActionPerformed
        // TODO add your handling code here:
        new NuevoUsuario().setVisible(true);
    }//GEN-LAST:event_Btn_Registrar_UsuarioActionPerformed

    private void Btn_Mostrar_ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Mostrar_ColaActionPerformed
        // TODO add your handling code here:
        ColaDoctor cola = new ColaDoctor();
        cola.setVisible(true);
    }//GEN-LAST:event_Btn_Mostrar_ColaActionPerformed

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);       
    }//GEN-LAST:event_Btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Mostrar_Cola;
    private javax.swing.JButton Btn_Registrar_Usuario;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JLabel Fondo;
    // End of variables declaration//GEN-END:variables
}
