/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author GerAr
 */
public class Inicio_Secretaria extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_Secretaria
     */
    public Inicio_Secretaria() {
        initComponents();
        Toolkit mipantalla = Toolkit.getDefaultToolkit(); // nos dice el medio donde esta compilando el programa
        Dimension tampantalla = mipantalla.getScreenSize(); // devuelve la dimension de la pantalla
        int altura = tampantalla.height, ancho = tampantalla.width;
        setLocation(ancho/4, altura/8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Salir = new javax.swing.JButton();
        Btn_Registrar_Cliente = new javax.swing.JButton();
        Btn_Factura = new javax.swing.JButton();
        Btn_Mostrar_Cola = new javax.swing.JButton();
        Btn_Factura1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_Salir.png"))); // NOI18N
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 100, 100));

        Btn_Registrar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_Registrar1.png"))); // NOI18N
        Btn_Registrar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Registrar_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 110, 190));

        Btn_Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_Factura.png"))); // NOI18N
        Btn_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FacturaActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 110, 190));

        Btn_Mostrar_Cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Bt_dog.png"))); // NOI18N
        Btn_Mostrar_Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Mostrar_ColaActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Mostrar_Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 110, 190));

        Btn_Factura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BuscarCliente.png"))); // NOI18N
        Btn_Factura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Factura1ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Factura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 110, 190));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo-Secretaria1.png"))); // NOI18N
        Fondo.setAlignmentY(0.0F);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 799, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void Btn_Registrar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_ClienteActionPerformed
        // TODO add your handling code here:
        new NuevoCliente().setVisible(true);
    }//GEN-LAST:event_Btn_Registrar_ClienteActionPerformed

    private void Btn_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FacturaActionPerformed
        // TODO add your handling code here:
        new Factura().setVisible(true);
    }//GEN-LAST:event_Btn_FacturaActionPerformed

    private void Btn_Mostrar_ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Mostrar_ColaActionPerformed
        // TODO add your handling code here:
        new ColaSecretaria().setVisible(true);
    }//GEN-LAST:event_Btn_Mostrar_ColaActionPerformed

    private void Btn_Factura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Factura1ActionPerformed
        // TODO add your handling code here:
        new ConsultaCliente().setVisible(true);
    }//GEN-LAST:event_Btn_Factura1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_Secretaria().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Factura;
    private javax.swing.JButton Btn_Factura1;
    private javax.swing.JButton Btn_Mostrar_Cola;
    private javax.swing.JButton Btn_Registrar_Cliente;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JLabel Fondo;
    // End of variables declaration//GEN-END:variables
}
