package Interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author usuario
 */
public class inicio_Doctor extends javax.swing.JFrame {

    /**
     * Creates new form inicio_Doctor
     */
    public inicio_Doctor() {
        initComponents();
        Toolkit mipantalla = Toolkit.getDefaultToolkit(); // nos dice el medio donde esta compilando el programa
        Dimension tampantalla = mipantalla.getScreenSize(); // devuelve la dimension de la pantalla
        int altura = tampantalla.height, ancho = tampantalla.width;
        setLocation(ancho/4, altura/8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Btn_cerrar_sesion = new javax.swing.JMenu();
        Btn_cola = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Btn_administrador = new javax.swing.JMenu();
        Registrar_Usuario = new javax.swing.JMenuItem();

        setResizable(false);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Inicio_administrador.png"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(780, 580));
        getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

        Btn_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_Salir.png"))); // NOI18N
        Btn_cerrar_sesion.setText("CERRAR SESION");
        Btn_cerrar_sesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_cerrar_sesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn_cerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_cerrar_sesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(Btn_cerrar_sesion);

        Btn_cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_Cola.png"))); // NOI18N
        Btn_cola.setText("MOSTRAR COLA");
        Btn_cola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_cola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn_cola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_colaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Btn_cola);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_diagnostico.png"))); // NOI18N
        jMenu2.setText("DIAGNOSTICO");
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu2);

        Btn_administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn_admin.png"))); // NOI18N
        Btn_administrador.setText("ADMINISTRADOR");
        Btn_administrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_administrador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Registrar_Usuario.setText("Registrar Usuario");
        Registrar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_UsuarioActionPerformed(evt);
            }
        });
        Btn_administrador.add(Registrar_Usuario);

        jMenuBar1.add(Btn_administrador);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Registrar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_UsuarioActionPerformed
        // TODO add your handling code here:
        NuevoUsuario nuevo = new NuevoUsuario();
        nuevo.setVisible(true);
    }//GEN-LAST:event_Registrar_UsuarioActionPerformed

    private void Btn_colaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_colaMouseClicked
        // TODO add your handling code here:
        ColaDoctor cola = new ColaDoctor();
        cola.setVisible(true);
    }//GEN-LAST:event_Btn_colaMouseClicked

    private void Btn_cerrar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cerrar_sesionMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_Btn_cerrar_sesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Btn_administrador;
    private javax.swing.JMenu Btn_cerrar_sesion;
    private javax.swing.JMenu Btn_cola;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenuItem Registrar_Usuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
