/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author User
 */
public class NuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsuario
     */
    public NuevoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevoUsuarioLbl = new javax.swing.JLabel();
        NombreLbl = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        ApPaternoLbl = new javax.swing.JLabel();
        ApPaternoTxt = new javax.swing.JTextField();
        ApMaternoLbl = new javax.swing.JLabel();
        ApMaternoTxt = new javax.swing.JTextField();
        UsuarioLbl = new javax.swing.JLabel();
        UsuarioTxt = new javax.swing.JTextField();
        PasswordLbl = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JTextField();
        TipoLbl = new javax.swing.JLabel();
        TipoComBox = new javax.swing.JComboBox<>();
        RegistrarBtn = new javax.swing.JButton();
        FondoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        NuevoUsuarioLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NuevoUsuarioLbl.setText("REGISTRO NUEVO USUARIO");
        getContentPane().add(NuevoUsuarioLbl);
        NuevoUsuarioLbl.setBounds(12, 22, 170, 15);

        NombreLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NombreLbl.setText("NOMBRE:");
        getContentPane().add(NombreLbl);
        NombreLbl.setBounds(12, 52, 100, 15);
        getContentPane().add(NombreTxt);
        NombreTxt.setBounds(150, 50, 230, 30);

        ApPaternoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ApPaternoLbl.setText("APELLIDO PATERNO:");
        getContentPane().add(ApPaternoLbl);
        ApPaternoLbl.setBounds(12, 84, 130, 15);
        getContentPane().add(ApPaternoTxt);
        ApPaternoTxt.setBounds(150, 80, 230, 30);

        ApMaternoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ApMaternoLbl.setText("APELLIDO MATERNO:");
        getContentPane().add(ApMaternoLbl);
        ApMaternoLbl.setBounds(12, 116, 130, 15);
        getContentPane().add(ApMaternoTxt);
        ApMaternoTxt.setBounds(150, 110, 230, 30);

        UsuarioLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UsuarioLbl.setText("USUARIO:");
        getContentPane().add(UsuarioLbl);
        UsuarioLbl.setBounds(12, 148, 110, 15);
        getContentPane().add(UsuarioTxt);
        UsuarioTxt.setBounds(150, 140, 230, 30);

        PasswordLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PasswordLbl.setText("PASSWORD:");
        getContentPane().add(PasswordLbl);
        PasswordLbl.setBounds(12, 180, 110, 15);
        getContentPane().add(PasswordTxt);
        PasswordTxt.setBounds(150, 170, 230, 30);

        TipoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TipoLbl.setText("TIPO:");
        getContentPane().add(TipoLbl);
        TipoLbl.setBounds(12, 214, 50, 15);

        TipoComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veterinario(a)", "Secretaria(o)" }));
        getContentPane().add(TipoComBox);
        TipoComBox.setBounds(150, 210, 100, 30);

        RegistrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/registro_opt.png"))); // NOI18N
        RegistrarBtn.setText("REGISTRAR");
        RegistrarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RegistrarBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(RegistrarBtn);
        RegistrarBtn.setBounds(270, 250, 100, 80);

        FondoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo.png"))); // NOI18N
        FondoLbl.setText("Nuevo Usuario");
        getContentPane().add(FondoLbl);
        FondoLbl.setBounds(0, 0, 420, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApMaternoLbl;
    private javax.swing.JTextField ApMaternoTxt;
    private javax.swing.JLabel ApPaternoLbl;
    private javax.swing.JTextField ApPaternoTxt;
    private javax.swing.JLabel FondoLbl;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel NuevoUsuarioLbl;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JButton RegistrarBtn;
    private javax.swing.JComboBox<String> TipoComBox;
    private javax.swing.JLabel TipoLbl;
    private javax.swing.JLabel UsuarioLbl;
    private javax.swing.JTextField UsuarioTxt;
    // End of variables declaration//GEN-END:variables
}
