/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Cliente;
import Clases.Identificador;
import Clases.Mascota;
import Database.Db_Atencion;
import Database.Db_Cliente;
import Database.Db_Mascota;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class NuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosPropietarioLbl = new javax.swing.JLabel();
        NombrePropLbl = new javax.swing.JLabel();
        NombrePropTxt = new javax.swing.JTextField();
        ApPaternoLbl = new javax.swing.JLabel();
        ApPaternoTxt = new javax.swing.JTextField();
        ApMaternoLbl = new javax.swing.JLabel();
        ApMaternoTxt = new javax.swing.JTextField();
        DniLbl = new javax.swing.JLabel();
        DniTxt = new javax.swing.JTextField();
        TelCelLbl = new javax.swing.JLabel();
        TelCelTxt = new javax.swing.JTextField();
        DireccionLbl = new javax.swing.JLabel();
        DireccionTxt = new javax.swing.JTextField();
        Separador = new javax.swing.JSeparator();
        DatosMascotaLbl = new javax.swing.JLabel();
        EspecieLbl = new javax.swing.JLabel();
        RazaLbl = new javax.swing.JLabel();
        RazaTxt = new javax.swing.JTextField();
        NombreMascotaLbl = new javax.swing.JLabel();
        NombreMascotaTxt = new javax.swing.JTextField();
        SexoLbl = new javax.swing.JLabel();
        SexoComBox = new javax.swing.JComboBox<>();
        FechaNacimientoLbl = new javax.swing.JLabel();
        FechNaciDataChooser = new com.toedter.calendar.JDateChooser();
        RegistrarBtn = new javax.swing.JButton();
        EspecieComBox = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(420, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        DatosPropietarioLbl.setText("DATOS DEL PROPIETARIO:");
        getContentPane().add(DatosPropietarioLbl);
        DatosPropietarioLbl.setBounds(12, 12, 180, 14);

        NombrePropLbl.setText("NOMBRES:");
        getContentPane().add(NombrePropLbl);
        NombrePropLbl.setBounds(12, 42, 100, 14);
        getContentPane().add(NombrePropTxt);
        NombrePropTxt.setBounds(142, 40, 266, 30);

        ApPaternoLbl.setText("APELLIDO PATERNO:");
        getContentPane().add(ApPaternoLbl);
        ApPaternoLbl.setBounds(12, 74, 130, 14);
        getContentPane().add(ApPaternoTxt);
        ApPaternoTxt.setBounds(142, 72, 266, 30);

        ApMaternoLbl.setText("APELLIDO MATERNO:");
        getContentPane().add(ApMaternoLbl);
        ApMaternoLbl.setBounds(12, 106, 130, 14);
        getContentPane().add(ApMaternoTxt);
        ApMaternoTxt.setBounds(144, 104, 264, 30);

        DniLbl.setText("DNI:");
        getContentPane().add(DniLbl);
        DniLbl.setBounds(12, 136, 70, 14);
        getContentPane().add(DniTxt);
        DniTxt.setBounds(144, 136, 264, 30);

        TelCelLbl.setText("TELEFONO/CELULAR:");
        getContentPane().add(TelCelLbl);
        TelCelLbl.setBounds(12, 170, 130, 14);
        getContentPane().add(TelCelTxt);
        TelCelTxt.setBounds(143, 168, 265, 30);

        DireccionLbl.setText("DIRECCION:");
        getContentPane().add(DireccionLbl);
        DireccionLbl.setBounds(12, 202, 100, 14);
        getContentPane().add(DireccionTxt);
        DireccionTxt.setBounds(143, 200, 265, 30);
        getContentPane().add(Separador);
        Separador.setBounds(10, 230, 396, 10);

        DatosMascotaLbl.setText("DATOS DE LA MASCOTA:");
        getContentPane().add(DatosMascotaLbl);
        DatosMascotaLbl.setBounds(12, 248, 160, 14);

        EspecieLbl.setText("ESPECIE:");
        getContentPane().add(EspecieLbl);
        EspecieLbl.setBounds(12, 278, 60, 14);

        RazaLbl.setText("RAZA:");
        getContentPane().add(RazaLbl);
        RazaLbl.setBounds(221, 278, 50, 14);
        getContentPane().add(RazaTxt);
        RazaTxt.setBounds(270, 270, 135, 30);

        NombreMascotaLbl.setText("NOMBRE:");
        getContentPane().add(NombreMascotaLbl);
        NombreMascotaLbl.setBounds(12, 312, 80, 14);
        getContentPane().add(NombreMascotaTxt);
        NombreMascotaTxt.setBounds(83, 310, 120, 30);

        SexoLbl.setText("SEXO:");
        getContentPane().add(SexoLbl);
        SexoLbl.setBounds(221, 312, 50, 14);

        SexoComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEMBRA", "MACHO" }));
        getContentPane().add(SexoComBox);
        SexoComBox.setBounds(274, 308, 100, 30);

        FechaNacimientoLbl.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(FechaNacimientoLbl);
        FechaNacimientoLbl.setBounds(12, 345, 150, 14);
        getContentPane().add(FechNaciDataChooser);
        FechNaciDataChooser.setBounds(156, 345, 127, 30);

        RegistrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/registro_opt.png"))); // NOI18N
        RegistrarBtn.setText("REGISTRAR");
        RegistrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarBtn);
        RegistrarBtn.setBounds(229, 388, 170, 53);

        EspecieComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERRO", "GATO", "CONEJO", "HAMSTER", "TORTUGA", "IGUANA" }));
        getContentPane().add(EspecieComBox);
        EspecieComBox.setBounds(80, 270, 120, 30);
        getContentPane().add(Fondo);
        Fondo.setBounds(0, -4, 440, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBtnActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        Mascota mascota = new Mascota();
        Db_Cliente db_cliente = new Db_Cliente();
        Db_Mascota db_mascota = new Db_Mascota();
        Identificador id=new Identificador();
        
        //Cliente
        cliente.setNombre(NombrePropTxt.getText());
        cliente.setApellidoPaterno(ApPaternoTxt.getText());
        cliente.setApellidoMaterno(ApMaternoTxt.getText());
        cliente.setDNI(Integer.parseInt(DniTxt.getText()));
        cliente.setDireccion(DireccionTxt.getText());
        cliente.setTelefono(Integer.parseInt(TelCelTxt.getText()));
        
        //Mascota
        mascota.setNombre(NombreMascotaTxt.getText());
        mascota.setEspecie((String) EspecieComBox.getSelectedItem());
        mascota.setRaza(RazaTxt.getText());
        mascota.setSexo((String) SexoComBox.getSelectedItem());
        String formato = FechNaciDataChooser.getDateFormatString();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        int dia = sdf.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = sdf.getCalendar().get(Calendar.MONTH);
        int anio = sdf.getCalendar().get(Calendar.YEAR);
        String fecha = dia+"-"+mes+"-"+anio;
        mascota.setFecha(fecha);
      
        int id_cliente;
        String ruta=null;
        try {
            db_cliente.insertar_Cliente(cliente.getNombre(),cliente.getApellidoPaterno(),
                    cliente.getApellidoMaterno(),cliente.getDNI(),cliente.getDireccion(),cliente.getTelefono());
            id_cliente = db_cliente.buscar_idCliente(cliente.getNombre(),cliente.getApellidoPaterno(),cliente.getApellidoMaterno());
            String codigo_mascota=id.Generar(mascota.getEspecie(), id_cliente);
            String id_fichero=String.valueOf(id_cliente);
            ruta = "D://Historiales/DOC"+id_fichero+".txt";
            db_mascota.insertar_Mascota(codigo_mascota,id_cliente, mascota.getNombre(),mascota.getEspecie(),
                mascota.getRaza(),mascota.getSexo(),mascota.getFecha(),ruta);
                
            File historial = new File(ruta);
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(historial))) {
                bw.write("HISTORIAL MEDICO \n"
                        + "Cliente:"+id_cliente+"");
                
                bw.close();
                
            }
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Db_Atencion db_atencion=new Db_Atencion();
        int resp=JOptionPane.showConfirmDialog(null, "¿Desea agregar al cliente registrado a la cola?");
        if(resp==0){
            try {
                db_atencion.Insertar_cola(cliente.getNombre(),cliente.getApellidoPaterno(),cliente.getApellidoMaterno(),
                        mascota.getNombre(),ruta);
            } catch (Exception ex) {
                Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        

        
        
        
    }//GEN-LAST:event_RegistrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApMaternoLbl;
    private javax.swing.JTextField ApMaternoTxt;
    private javax.swing.JLabel ApPaternoLbl;
    private javax.swing.JTextField ApPaternoTxt;
    private javax.swing.JLabel DatosMascotaLbl;
    private javax.swing.JLabel DatosPropietarioLbl;
    private javax.swing.JLabel DireccionLbl;
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.JLabel DniLbl;
    private javax.swing.JTextField DniTxt;
    private javax.swing.JComboBox<String> EspecieComBox;
    private javax.swing.JLabel EspecieLbl;
    private com.toedter.calendar.JDateChooser FechNaciDataChooser;
    private javax.swing.JLabel FechaNacimientoLbl;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NombreMascotaLbl;
    private javax.swing.JTextField NombreMascotaTxt;
    private javax.swing.JLabel NombrePropLbl;
    private javax.swing.JTextField NombrePropTxt;
    private javax.swing.JLabel RazaLbl;
    private javax.swing.JTextField RazaTxt;
    private javax.swing.JButton RegistrarBtn;
    private javax.swing.JSeparator Separador;
    private javax.swing.JComboBox<String> SexoComBox;
    private javax.swing.JLabel SexoLbl;
    private javax.swing.JLabel TelCelLbl;
    private javax.swing.JTextField TelCelTxt;
    // End of variables declaration//GEN-END:variables
}
